application:
   title: Track2BSky
   version: v1.0

spring:
  security:
    user:
      name: admin
      password: $2a$10$YgEE0XpMb0vjEbhmNt59UOhk5KTCiIHfaHL2THfPFUhdt8qgxrSOe

server:
    servlet:
        context-path: /track2bsky
    port: 8080

app:
    track2bsky:
        internal_token: XWF211DSQDM13DH81327
    bluesky:
        url: https://bsky.social/xrpc
        identifier: IDENTIFIER
        password: PASSWORD
    spotify:
        url: https://api.spotify.com/v1
        accounts_url: https://accounts.spotify.com
        client_id: CLIENT_ID
        client_secret: CLIENT_SECRET
        redirect_uri: http://localhost:8080/track2bsky/spotify/callback
        scopes: user-read-private user-read-email user-read-playback-state user-modify-playback-state user-read-currently-playing

logging:
    level:
        org.springframework: INFO
        com.track2bsky: DEBUG


